version: "3.8"


networks:
  webapp:
services:
  truecomment:
    build:
      context: .
    ports:
      - 8888:8888
    networks:
      - webapp  
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
     - ./data/db:/var/lib/mysql
    networks:
      - webapp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:80
    volumes:
     - /sessions
    networks:
      - webapp 
