version: "3.8"


networks:
  webapp:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/24
services:
  truecomment:
    build:
      context: .
    ports:
      - 8887:8887
    networks:
      webapp:
        ipv4_address: 172.22.0.19 
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
     - ./data/db:/var/lib/mysql
    networks:
      webapp:
        ipv4_address: 172.22.0.20

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:80
    volumes:
     - /sessions
    networks:
      - webapp 
